# Generated by Django 5.1.7 on 2025-04-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_alter_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
