# Generated by Django 5.1.7 on 2025-04-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0003_transaction_category_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ref_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
