# Generated by Django 5.1.7 on 2025-04-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0004_transaction_ref_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ref_number',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
