# Generated by Django 5.1.7 on 2025-04-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0006_transaction_ref_number_alter_transaction_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('sms', 'SMS'), ('ocr', 'OCR'), ('manual', 'Manual')], default='manual', max_length=50),
        ),
    ]
