const categoryMap = {
  "Blinkit": "Shopping",
  "British": "Food",
  "waffle": "Food",
  "PRINTER": "Stationary",
  "Indian Railways": "Travel",
  "S MART": "Shopping",
  "MART": "Shopping",
  "IRCTC UTS": "Travel",
  "Swiggy": "Food",
  "Suraj Lama Momos": "Food",
  "Momos": "Food",
  "CMP PPI Wallet L": "Bills",
  "Milk": "Food",
  "Bharat Gas": "Bills",
  "SAMRAT ENTERPRIS": "Shopping",
  "health": "Health",
  "REVOLUCE HEALTHC": "Health",
  "zepto": "Shopping",
  "super": "Shopping",
  "BHAVANI SWEETS": "Food",
  "SWEETS": "Food",
  "GROCERY": "Shopping",
  "food": "Food",
  "BALMUKUND FOODS": "Food",
  "MC DONALDS": "Food",
  "MCDONALDS": "Food",
  "dominos": "Food",
  "Google India Dig": "Shopping",
  "ZOMATO": "Food",
  'netflix': "Entertainment",
  'amazon': "Shopping",
  'amazon prime': "Entertainment",
  'prime': "Entertainment",
  'hotstar': "Entertainment",
  'disney': "Entertainment",
  "NOSTALGIA": "Food",
  "cheap jack gener": "Shopping",
  "FREDDYS": "Food",
  "KISAN": "Shopping",
  "GROFERS": "Shopping",
  'coffee': "Food",
  "IndianClearingCo": "Bills",
  "GOOGLE INDIA DIGITAL SERVICES PVT LTD": "Shopping",
  "NOBLE CHEMIST": "Health",
  "GOENKA AND ASSOC": "Health",
  "hospital": "Health",
  "Drogheria Seller": "Shopping",
  "seller": "Shopping",
  "Indian Clearing": "Bills",
  "AJIO": "Shopping",
  "Swiggy": "Food",
  "YMI GHAR SOAPS P": "Shopping",
  "SAI BHAJI VIKRI": "Shopping",
  "Bhaji": "Shopping",
  "Chalo": "Travel",
  "masa": "Food",
  "HT MEDIA LTD": "Entertainment",
  "ANUPAM STATIONER": "Stationary",
  "Dresses": "Shopping",
  "ENTERPRISE": "Shopping",
  "JANTA": "Shopping",
  "RAMBHAROSESWEETS": "Food",
  "Kala sangam Nx": "Shopping",
  "Indigo": "Travel",
  "JIO": "Bills",
  "sandwich": "Food",
  "ZERODHA": "bills",
  "HARDCASTLE": "Food",
};

  
  // Function to categorize merchant name
  export const categorizeMerchant = (merchantName) => {
    const normalizedName = merchantName.toUpperCase();
    for (const keyword in categoryMap) {
        if (normalizedName.includes(keyword.toUpperCase())) {
        return categoryMap[keyword];
        }
    }
    return "Unknown";  
    };